services:
  scheduler:
    image: "jabriel/sneks:3.9.10-slim"
    environment:
      - PIP_PACKAGES=poetry dask distributed
    command: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
  worker-1:
    image: "jabriel/sneks:3.9.10-slim"
    environment:
      - PIP_PACKAGES=poetry dask distributed
    command: dask-worker tcp://scheduler:8786
    depends_on:
      - scheduler
  worker-2:
    image: "jabriel/sneks:3.9.10-slim"
    environment:
      - PIP_PACKAGES=poetry dask distributed
    command: dask-worker tcp://scheduler:8786
    depends_on:
      - scheduler
