repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
        args:
          - --target-version=py38
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: node
        pass_filenames: true
        types: [python]
ci:
  skip:
    - "pyright"
